# Generated by Django 3.2.4 on 2021-06-02 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicians_name', models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(3)])),
                ('musicians_type', models.CharField(choices=[('V', 'Vocalist'), ('I', 'Instrumentalist')], max_length=2)),
                ('album_albums', models.ManyToManyField(to='albums.MusicAlbums')),
            ],
            options={
                'verbose_name': 'Musician',
                'verbose_name_plural': 'Musicians',
            },
        ),
    ]
