# Generated by Django 3.2.4 on 2021-06-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_musicalbums_album_musicians'),
        ('musicians', '0002_alter_musicians_musicians_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='album_albums',
            field=models.ManyToManyField(blank=True, null=True, to='albums.MusicAlbums'),
        ),
    ]
