# Generated by Django 3.2.4 on 2021-06-02 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0003_alter_musicians_album_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='musicians_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Name should be minimum 3 characters')]),
        ),
    ]
