# Generated by Django 3.2.4 on 2021-06-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0004_alter_musicians_musicians_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicians',
            name='album_albums',
        ),
    ]
