# Generated by Django 3.2.4 on 2021-06-05 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0005_remove_musicians_album_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicians',
            name='musicians_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
