# Generated by Django 3.2.4 on 2021-06-02 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAlbums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(5)])),
                ('album_release_date', models.DateField(choices=[('CM', 'Country music'), ('EM', 'Electronic music'), ('RM', 'Rock music'), ('HM', 'Hip hop music'), ('LM', 'Latin music'), ('PM', 'Pop music')], max_length=2)),
                ('album_genre', models.CharField(max_length=100)),
                ('album_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)])),
                ('album_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Music Album',
                'verbose_name_plural': 'Music Albums',
            },
        ),
    ]
