# Generated by Django 3.2.4 on 2021-06-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicians', '0001_initial'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbums',
            name='album_musicians',
            field=models.ManyToManyField(to='musicians.Musicians'),
        ),
    ]
