# Generated by Django 3.2.4 on 2021-06-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_musicalbums_album_musicians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalbums',
            name='album_genre',
            field=models.CharField(choices=[('CM', 'Country music'), ('EM', 'Electronic music'), ('RM', 'Rock music'), ('HM', 'Hip hop music'), ('LM', 'Latin music'), ('PM', 'Pop music')], max_length=2),
        ),
        migrations.AlterField(
            model_name='musicalbums',
            name='album_release_date',
            field=models.DateField(),
        ),
    ]
