# Generated by Django 3.2.4 on 2021-06-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0002_alter_musicians_musicians_name'),
        ('albums', '0004_alter_musicalbums_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalbums',
            name='album_musicians',
            field=models.ManyToManyField(blank=True, null=True, to='musicians.Musicians'),
        ),
    ]
