# Generated by Django 3.2.4 on 2021-06-02 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_musicalbums_album_musicians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalbums',
            name='album_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, message='Album Name should be minimum 5 characters')]),
        ),
    ]
