# Generated by Django 3.2.4 on 2021-06-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_musicalbums_album_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicalbums',
            name='album_musicians',
        ),
    ]
