# Generated by Django 3.2.4 on 2021-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0005_remove_musicians_album_albums'),
        ('albums', '0007_remove_musicalbums_album_musicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbums',
            name='album_musicians',
            field=models.ManyToManyField(blank=True, null=True, to='musicians.Musicians'),
        ),
    ]
