# Generated by Django 3.2.4 on 2021-06-05 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0006_musicians_musicians_token'),
        ('albums', '0008_musicalbums_album_musicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbums',
            name='album_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='musicalbums',
            name='album_musicians',
            field=models.ManyToManyField(blank=True, to='musicians.Musicians'),
        ),
    ]
